### ISSUE TITLE
Pretrained GloVe Embeddings文件下载不成功

### ISSUE THREAD

**Issue by 991126** [wlr737/EMNLP2022-SEEK#1]
你好，这个 Pretrained GloVe Embeddings文件下载不成功，能够重新上传一份呢？谢谢

**Comment by wlr737** [comment]
已收到您的邮件，祝生活愉快！！

**Comment by 991126** [comment]
邮件收到啦，但是我点进链接之后，一直显示下载文件时出现错误

**Comment by wlr737** [comment]
https://www.kaggle.com/datasets/thanakomsn/glove6b300dtxt

**Comment by 991126** [comment]
谢谢，真是麻烦了，已经成功下载好啦！
