### ISSUE TITLE
How can I view the code content of the "dataset_preproc.p" file?

### ISSUE THREAD

**Issue by juanmaoxiongmaoQAQ** [wlr737/EMNLP2022-SEEK#4]
Hi，
First of all thank you for your contribution in empathic dialogue generation！
Great work for SEEK!
I want to check how you preprocess the data, but I don't know how to open the "dataset_preproc.p" file. How can I check the specific preprocessing method?
Thank you very much, looking forward to your reply！

您好，
首先感谢您在共情对话生成方面的贡献！
SEEK是伟大的工作！
我想查看您是如何预处理数据，但是我不知道如何打开"dataset_preproc.p"文件，请问我该如何操作才能查看具体预处理的方法呢？
十分感谢，期待您的回复！

**Comment by wlr737** [comment]
Use load_dataset() function in ./src/utils/data/loader.py to load the binary file "dataset_preproc.p".

**Comment by juanmaoxiongmaoQAQ** [comment]
You may not understand what I mean. In ./src/utils/data/loader.py, I saw that the binary file "dataset_preproc.p" is loaded, and [data_tra, data_val, data_tst, vocab] is returned after the code is executed, but I I don't know why the returned data_tra looks like that,for example, how to get "emotion_context", so I want to know the original data preprocessing process, but I don't know how to do it.

您可能没理解我的意思，在./src/utils/data/loader.py中我看到了加载二进制文件"dataset_preproc.p"，代码执行后返回了[data_tra, data_val, data_tst, vocab]，但我不知道为什么返回的data_tra是长那个样子，比如“emotion_context”是怎么得到的，所以想知道其中的原始数据预处理过程，然而我并不知道怎么操作。

![微信图片_20230414124952](https://user-images.githubusercontent.com/80947109/231944686-3f27c7a6-7739-47e9-a30a-88b74dad3e1f.png)
